/*
 * OpenProject API v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.jbw.openproject.client.model.ApiV3CustomActionsCustomActionIdExecuteLinks;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * InlineObject1
 */
@JsonPropertyOrder({
  InlineObject1.JSON_PROPERTY_LOCK_VERSION,
  InlineObject1.JSON_PROPERTY_LINKS
})

public class InlineObject1 {
  public static final String JSON_PROPERTY_LOCK_VERSION = "lockVersion";
  private String lockVersion;

  public static final String JSON_PROPERTY_LINKS = "_links";
  private ApiV3CustomActionsCustomActionIdExecuteLinks links;


  public InlineObject1 lockVersion(String lockVersion) {
    
    this.lockVersion = lockVersion;
    return this;
  }

   /**
   * Get lockVersion
   * @return lockVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCK_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLockVersion() {
    return lockVersion;
  }


  public void setLockVersion(String lockVersion) {
    this.lockVersion = lockVersion;
  }


  public InlineObject1 links(ApiV3CustomActionsCustomActionIdExecuteLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ApiV3CustomActionsCustomActionIdExecuteLinks getLinks() {
    return links;
  }


  public void setLinks(ApiV3CustomActionsCustomActionIdExecuteLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return Objects.equals(this.lockVersion, inlineObject1.lockVersion) &&
        Objects.equals(this.links, inlineObject1.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lockVersion, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    sb.append("    lockVersion: ").append(toIndentedString(lockVersion)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

