/*
 * OpenProject API v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import net.jbw.openproject.client.model.Link;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TimeEntriesLinks
 */
@JsonPropertyOrder({
  TimeEntriesLinks.JSON_PROPERTY_SELF,
  TimeEntriesLinks.JSON_PROPERTY_JUMP_TO,
  TimeEntriesLinks.JSON_PROPERTY_CHANGE_SIZE,
  TimeEntriesLinks.JSON_PROPERTY_NEXT_BY_OFFSET
})

public class TimeEntriesLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  private Link self;

  public static final String JSON_PROPERTY_JUMP_TO = "jumpTo";
  private Link jumpTo;

  public static final String JSON_PROPERTY_CHANGE_SIZE = "changeSize";
  private Link changeSize;

  public static final String JSON_PROPERTY_NEXT_BY_OFFSET = "nextByOffset";
  private Link nextByOffset;


  public TimeEntriesLinks self(Link self) {
    
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getSelf() {
    return self;
  }


  public void setSelf(Link self) {
    this.self = self;
  }


  public TimeEntriesLinks jumpTo(Link jumpTo) {
    
    this.jumpTo = jumpTo;
    return this;
  }

   /**
   * Get jumpTo
   * @return jumpTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JUMP_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getJumpTo() {
    return jumpTo;
  }


  public void setJumpTo(Link jumpTo) {
    this.jumpTo = jumpTo;
  }


  public TimeEntriesLinks changeSize(Link changeSize) {
    
    this.changeSize = changeSize;
    return this;
  }

   /**
   * Get changeSize
   * @return changeSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHANGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getChangeSize() {
    return changeSize;
  }


  public void setChangeSize(Link changeSize) {
    this.changeSize = changeSize;
  }


  public TimeEntriesLinks nextByOffset(Link nextByOffset) {
    
    this.nextByOffset = nextByOffset;
    return this;
  }

   /**
   * Get nextByOffset
   * @return nextByOffset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT_BY_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getNextByOffset() {
    return nextByOffset;
  }


  public void setNextByOffset(Link nextByOffset) {
    this.nextByOffset = nextByOffset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeEntriesLinks timeEntriesLinks = (TimeEntriesLinks) o;
    return Objects.equals(this.self, timeEntriesLinks.self) &&
        Objects.equals(this.jumpTo, timeEntriesLinks.jumpTo) &&
        Objects.equals(this.changeSize, timeEntriesLinks.changeSize) &&
        Objects.equals(this.nextByOffset, timeEntriesLinks.nextByOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, jumpTo, changeSize, nextByOffset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeEntriesLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    jumpTo: ").append(toIndentedString(jumpTo)).append("\n");
    sb.append("    changeSize: ").append(toIndentedString(changeSize)).append("\n");
    sb.append("    nextByOffset: ").append(toIndentedString(nextByOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

