/*
 * OpenProject API v3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import net.jbw.openproject.client.model.Link;
/**
 * TimeEntryLinks
 */


public class TimeEntryLinks {
  @SerializedName("self")
  private Link self = null;

  @SerializedName("project")
  private Link project = null;

  @SerializedName("workPackage")
  private Link workPackage = null;

  @SerializedName("user")
  private Link user = null;

  @SerializedName("activity")
  private Link activity = null;

  public TimeEntryLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }

  public TimeEntryLinks project(Link project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @Schema(description = "")
  public Link getProject() {
    return project;
  }

  public void setProject(Link project) {
    this.project = project;
  }

  public TimeEntryLinks workPackage(Link workPackage) {
    this.workPackage = workPackage;
    return this;
  }

   /**
   * Get workPackage
   * @return workPackage
  **/
  @Schema(description = "")
  public Link getWorkPackage() {
    return workPackage;
  }

  public void setWorkPackage(Link workPackage) {
    this.workPackage = workPackage;
  }

  public TimeEntryLinks user(Link user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public Link getUser() {
    return user;
  }

  public void setUser(Link user) {
    this.user = user;
  }

  public TimeEntryLinks activity(Link activity) {
    this.activity = activity;
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  @Schema(description = "")
  public Link getActivity() {
    return activity;
  }

  public void setActivity(Link activity) {
    this.activity = activity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeEntryLinks timeEntryLinks = (TimeEntryLinks) o;
    return Objects.equals(this.self, timeEntryLinks.self) &&
        Objects.equals(this.project, timeEntryLinks.project) &&
        Objects.equals(this.workPackage, timeEntryLinks.workPackage) &&
        Objects.equals(this.user, timeEntryLinks.user) &&
        Objects.equals(this.activity, timeEntryLinks.activity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, project, workPackage, user, activity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeEntryLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    workPackage: ").append(toIndentedString(workPackage)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
