/*
 * OpenProject API v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.jbw.openproject.client.model.Link;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WorkPackageLinks
 */
@JsonPropertyOrder({
  WorkPackageLinks.JSON_PROPERTY_SELF,
  WorkPackageLinks.JSON_PROPERTY_UPDATE,
  WorkPackageLinks.JSON_PROPERTY_SCHEMA,
  WorkPackageLinks.JSON_PROPERTY_UPDATE_IMMEDIATELY,
  WorkPackageLinks.JSON_PROPERTY_LOG_TIME,
  WorkPackageLinks.JSON_PROPERTY_MOVE,
  WorkPackageLinks.JSON_PROPERTY_COPY,
  WorkPackageLinks.JSON_PROPERTY_PDF,
  WorkPackageLinks.JSON_PROPERTY_ATOM,
  WorkPackageLinks.JSON_PROPERTY_AVAILABLE_RELATION_CANDIDATES,
  WorkPackageLinks.JSON_PROPERTY_ACTIVITIES,
  WorkPackageLinks.JSON_PROPERTY_ATTACHMENTS,
  WorkPackageLinks.JSON_PROPERTY_ADD_ATTACHMENT,
  WorkPackageLinks.JSON_PROPERTY_AVAILABLE_WATCHERS,
  WorkPackageLinks.JSON_PROPERTY_RELATIONS,
  WorkPackageLinks.JSON_PROPERTY_REVISIONS,
  WorkPackageLinks.JSON_PROPERTY_WATCH,
  WorkPackageLinks.JSON_PROPERTY_WATCHERS,
  WorkPackageLinks.JSON_PROPERTY_ADD_WATCHER,
  WorkPackageLinks.JSON_PROPERTY_REMOVE_WATCHER,
  WorkPackageLinks.JSON_PROPERTY_ADD_RELATION,
  WorkPackageLinks.JSON_PROPERTY_ADD_CHILD,
  WorkPackageLinks.JSON_PROPERTY_CHANGE_PARENT,
  WorkPackageLinks.JSON_PROPERTY_ADD_COMMENT,
  WorkPackageLinks.JSON_PROPERTY_PREVIEW_MARKUP,
  WorkPackageLinks.JSON_PROPERTY_TIME_ENTRIES,
  WorkPackageLinks.JSON_PROPERTY_ANCESTORS,
  WorkPackageLinks.JSON_PROPERTY_CATEGORY,
  WorkPackageLinks.JSON_PROPERTY_TYPE,
  WorkPackageLinks.JSON_PROPERTY_PRIORITY,
  WorkPackageLinks.JSON_PROPERTY_PROJECT,
  WorkPackageLinks.JSON_PROPERTY_STATUS,
  WorkPackageLinks.JSON_PROPERTY_AUTHOR,
  WorkPackageLinks.JSON_PROPERTY_RESPONSIBLE,
  WorkPackageLinks.JSON_PROPERTY_ASSIGNEE,
  WorkPackageLinks.JSON_PROPERTY_VERSION,
  WorkPackageLinks.JSON_PROPERTY_PARENT,
  WorkPackageLinks.JSON_PROPERTY_LOG_COSTS,
  WorkPackageLinks.JSON_PROPERTY_SHOW_COSTS,
  WorkPackageLinks.JSON_PROPERTY_COST_OBJECT,
  WorkPackageLinks.JSON_PROPERTY_COSTS_BY_TYPE
})

public class WorkPackageLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  private Link self;

  public static final String JSON_PROPERTY_UPDATE = "update";
  private Link update;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  private Link schema;

  public static final String JSON_PROPERTY_UPDATE_IMMEDIATELY = "updateImmediately";
  private Link updateImmediately;

  public static final String JSON_PROPERTY_LOG_TIME = "logTime";
  private Link logTime;

  public static final String JSON_PROPERTY_MOVE = "move";
  private Link move;

  public static final String JSON_PROPERTY_COPY = "copy";
  private Link copy;

  public static final String JSON_PROPERTY_PDF = "pdf";
  private Link pdf;

  public static final String JSON_PROPERTY_ATOM = "atom";
  private Link atom;

  public static final String JSON_PROPERTY_AVAILABLE_RELATION_CANDIDATES = "available_relation_candidates";
  private Link availableRelationCandidates;

  public static final String JSON_PROPERTY_ACTIVITIES = "activities";
  private Link activities;

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  private Link attachments;

  public static final String JSON_PROPERTY_ADD_ATTACHMENT = "addAttachment";
  private Link addAttachment;

  public static final String JSON_PROPERTY_AVAILABLE_WATCHERS = "availableWatchers";
  private Link availableWatchers;

  public static final String JSON_PROPERTY_RELATIONS = "relations";
  private Link relations;

  public static final String JSON_PROPERTY_REVISIONS = "revisions";
  private Link revisions;

  public static final String JSON_PROPERTY_WATCH = "watch";
  private Link watch;

  public static final String JSON_PROPERTY_WATCHERS = "watchers";
  private Link watchers;

  public static final String JSON_PROPERTY_ADD_WATCHER = "addWatcher";
  private Link addWatcher;

  public static final String JSON_PROPERTY_REMOVE_WATCHER = "removeWatcher";
  private Link removeWatcher;

  public static final String JSON_PROPERTY_ADD_RELATION = "addRelation";
  private Link addRelation;

  public static final String JSON_PROPERTY_ADD_CHILD = "addChild";
  private Link addChild;

  public static final String JSON_PROPERTY_CHANGE_PARENT = "changeParent";
  private Link changeParent;

  public static final String JSON_PROPERTY_ADD_COMMENT = "addComment";
  private Link addComment;

  public static final String JSON_PROPERTY_PREVIEW_MARKUP = "previewMarkup";
  private Link previewMarkup;

  public static final String JSON_PROPERTY_TIME_ENTRIES = "timeEntries";
  private Link timeEntries;

  public static final String JSON_PROPERTY_ANCESTORS = "ancestors";
  private List<Link> ancestors = null;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private Link category;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Link type;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Link priority;

  public static final String JSON_PROPERTY_PROJECT = "project";
  private Link project;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Link status;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  private Link author;

  public static final String JSON_PROPERTY_RESPONSIBLE = "responsible";
  private Link responsible;

  public static final String JSON_PROPERTY_ASSIGNEE = "assignee";
  private Link assignee;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Link version;

  public static final String JSON_PROPERTY_PARENT = "parent";
  private Link parent;

  public static final String JSON_PROPERTY_LOG_COSTS = "logCosts";
  private Link logCosts;

  public static final String JSON_PROPERTY_SHOW_COSTS = "showCosts";
  private Link showCosts;

  public static final String JSON_PROPERTY_COST_OBJECT = "costObject";
  private Link costObject;

  public static final String JSON_PROPERTY_COSTS_BY_TYPE = "costsByType";
  private Link costsByType;


  public WorkPackageLinks self(Link self) {
    
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getSelf() {
    return self;
  }


  public void setSelf(Link self) {
    this.self = self;
  }


  public WorkPackageLinks update(Link update) {
    
    this.update = update;
    return this;
  }

   /**
   * Get update
   * @return update
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getUpdate() {
    return update;
  }


  public void setUpdate(Link update) {
    this.update = update;
  }


  public WorkPackageLinks schema(Link schema) {
    
    this.schema = schema;
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getSchema() {
    return schema;
  }


  public void setSchema(Link schema) {
    this.schema = schema;
  }


  public WorkPackageLinks updateImmediately(Link updateImmediately) {
    
    this.updateImmediately = updateImmediately;
    return this;
  }

   /**
   * Get updateImmediately
   * @return updateImmediately
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_IMMEDIATELY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getUpdateImmediately() {
    return updateImmediately;
  }


  public void setUpdateImmediately(Link updateImmediately) {
    this.updateImmediately = updateImmediately;
  }


  public WorkPackageLinks logTime(Link logTime) {
    
    this.logTime = logTime;
    return this;
  }

   /**
   * Get logTime
   * @return logTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOG_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getLogTime() {
    return logTime;
  }


  public void setLogTime(Link logTime) {
    this.logTime = logTime;
  }


  public WorkPackageLinks move(Link move) {
    
    this.move = move;
    return this;
  }

   /**
   * Get move
   * @return move
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MOVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getMove() {
    return move;
  }


  public void setMove(Link move) {
    this.move = move;
  }


  public WorkPackageLinks copy(Link copy) {
    
    this.copy = copy;
    return this;
  }

   /**
   * Get copy
   * @return copy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COPY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getCopy() {
    return copy;
  }


  public void setCopy(Link copy) {
    this.copy = copy;
  }


  public WorkPackageLinks pdf(Link pdf) {
    
    this.pdf = pdf;
    return this;
  }

   /**
   * Get pdf
   * @return pdf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PDF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getPdf() {
    return pdf;
  }


  public void setPdf(Link pdf) {
    this.pdf = pdf;
  }


  public WorkPackageLinks atom(Link atom) {
    
    this.atom = atom;
    return this;
  }

   /**
   * Get atom
   * @return atom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAtom() {
    return atom;
  }


  public void setAtom(Link atom) {
    this.atom = atom;
  }


  public WorkPackageLinks availableRelationCandidates(Link availableRelationCandidates) {
    
    this.availableRelationCandidates = availableRelationCandidates;
    return this;
  }

   /**
   * Get availableRelationCandidates
   * @return availableRelationCandidates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AVAILABLE_RELATION_CANDIDATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAvailableRelationCandidates() {
    return availableRelationCandidates;
  }


  public void setAvailableRelationCandidates(Link availableRelationCandidates) {
    this.availableRelationCandidates = availableRelationCandidates;
  }


  public WorkPackageLinks activities(Link activities) {
    
    this.activities = activities;
    return this;
  }

   /**
   * Get activities
   * @return activities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTIVITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getActivities() {
    return activities;
  }


  public void setActivities(Link activities) {
    this.activities = activities;
  }


  public WorkPackageLinks attachments(Link attachments) {
    
    this.attachments = attachments;
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAttachments() {
    return attachments;
  }


  public void setAttachments(Link attachments) {
    this.attachments = attachments;
  }


  public WorkPackageLinks addAttachment(Link addAttachment) {
    
    this.addAttachment = addAttachment;
    return this;
  }

   /**
   * Get addAttachment
   * @return addAttachment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_ATTACHMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAddAttachment() {
    return addAttachment;
  }


  public void setAddAttachment(Link addAttachment) {
    this.addAttachment = addAttachment;
  }


  public WorkPackageLinks availableWatchers(Link availableWatchers) {
    
    this.availableWatchers = availableWatchers;
    return this;
  }

   /**
   * Get availableWatchers
   * @return availableWatchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AVAILABLE_WATCHERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAvailableWatchers() {
    return availableWatchers;
  }


  public void setAvailableWatchers(Link availableWatchers) {
    this.availableWatchers = availableWatchers;
  }


  public WorkPackageLinks relations(Link relations) {
    
    this.relations = relations;
    return this;
  }

   /**
   * Get relations
   * @return relations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getRelations() {
    return relations;
  }


  public void setRelations(Link relations) {
    this.relations = relations;
  }


  public WorkPackageLinks revisions(Link revisions) {
    
    this.revisions = revisions;
    return this;
  }

   /**
   * Get revisions
   * @return revisions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVISIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getRevisions() {
    return revisions;
  }


  public void setRevisions(Link revisions) {
    this.revisions = revisions;
  }


  public WorkPackageLinks watch(Link watch) {
    
    this.watch = watch;
    return this;
  }

   /**
   * Get watch
   * @return watch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getWatch() {
    return watch;
  }


  public void setWatch(Link watch) {
    this.watch = watch;
  }


  public WorkPackageLinks watchers(Link watchers) {
    
    this.watchers = watchers;
    return this;
  }

   /**
   * Get watchers
   * @return watchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WATCHERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getWatchers() {
    return watchers;
  }


  public void setWatchers(Link watchers) {
    this.watchers = watchers;
  }


  public WorkPackageLinks addWatcher(Link addWatcher) {
    
    this.addWatcher = addWatcher;
    return this;
  }

   /**
   * Get addWatcher
   * @return addWatcher
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_WATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAddWatcher() {
    return addWatcher;
  }


  public void setAddWatcher(Link addWatcher) {
    this.addWatcher = addWatcher;
  }


  public WorkPackageLinks removeWatcher(Link removeWatcher) {
    
    this.removeWatcher = removeWatcher;
    return this;
  }

   /**
   * Get removeWatcher
   * @return removeWatcher
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REMOVE_WATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getRemoveWatcher() {
    return removeWatcher;
  }


  public void setRemoveWatcher(Link removeWatcher) {
    this.removeWatcher = removeWatcher;
  }


  public WorkPackageLinks addRelation(Link addRelation) {
    
    this.addRelation = addRelation;
    return this;
  }

   /**
   * Get addRelation
   * @return addRelation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAddRelation() {
    return addRelation;
  }


  public void setAddRelation(Link addRelation) {
    this.addRelation = addRelation;
  }


  public WorkPackageLinks addChild(Link addChild) {
    
    this.addChild = addChild;
    return this;
  }

   /**
   * Get addChild
   * @return addChild
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_CHILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAddChild() {
    return addChild;
  }


  public void setAddChild(Link addChild) {
    this.addChild = addChild;
  }


  public WorkPackageLinks changeParent(Link changeParent) {
    
    this.changeParent = changeParent;
    return this;
  }

   /**
   * Get changeParent
   * @return changeParent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHANGE_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getChangeParent() {
    return changeParent;
  }


  public void setChangeParent(Link changeParent) {
    this.changeParent = changeParent;
  }


  public WorkPackageLinks addComment(Link addComment) {
    
    this.addComment = addComment;
    return this;
  }

   /**
   * Get addComment
   * @return addComment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAddComment() {
    return addComment;
  }


  public void setAddComment(Link addComment) {
    this.addComment = addComment;
  }


  public WorkPackageLinks previewMarkup(Link previewMarkup) {
    
    this.previewMarkup = previewMarkup;
    return this;
  }

   /**
   * Get previewMarkup
   * @return previewMarkup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PREVIEW_MARKUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getPreviewMarkup() {
    return previewMarkup;
  }


  public void setPreviewMarkup(Link previewMarkup) {
    this.previewMarkup = previewMarkup;
  }


  public WorkPackageLinks timeEntries(Link timeEntries) {
    
    this.timeEntries = timeEntries;
    return this;
  }

   /**
   * Get timeEntries
   * @return timeEntries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getTimeEntries() {
    return timeEntries;
  }


  public void setTimeEntries(Link timeEntries) {
    this.timeEntries = timeEntries;
  }


  public WorkPackageLinks ancestors(List<Link> ancestors) {
    
    this.ancestors = ancestors;
    return this;
  }

  public WorkPackageLinks addAncestorsItem(Link ancestorsItem) {
    if (this.ancestors == null) {
      this.ancestors = new ArrayList<>();
    }
    this.ancestors.add(ancestorsItem);
    return this;
  }

   /**
   * Get ancestors
   * @return ancestors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ANCESTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getAncestors() {
    return ancestors;
  }


  public void setAncestors(List<Link> ancestors) {
    this.ancestors = ancestors;
  }


  public WorkPackageLinks category(Link category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getCategory() {
    return category;
  }


  public void setCategory(Link category) {
    this.category = category;
  }


  public WorkPackageLinks type(Link type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getType() {
    return type;
  }


  public void setType(Link type) {
    this.type = type;
  }


  public WorkPackageLinks priority(Link priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getPriority() {
    return priority;
  }


  public void setPriority(Link priority) {
    this.priority = priority;
  }


  public WorkPackageLinks project(Link project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getProject() {
    return project;
  }


  public void setProject(Link project) {
    this.project = project;
  }


  public WorkPackageLinks status(Link status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getStatus() {
    return status;
  }


  public void setStatus(Link status) {
    this.status = status;
  }


  public WorkPackageLinks author(Link author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAuthor() {
    return author;
  }


  public void setAuthor(Link author) {
    this.author = author;
  }


  public WorkPackageLinks responsible(Link responsible) {
    
    this.responsible = responsible;
    return this;
  }

   /**
   * Get responsible
   * @return responsible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESPONSIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getResponsible() {
    return responsible;
  }


  public void setResponsible(Link responsible) {
    this.responsible = responsible;
  }


  public WorkPackageLinks assignee(Link assignee) {
    
    this.assignee = assignee;
    return this;
  }

   /**
   * Get assignee
   * @return assignee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ASSIGNEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getAssignee() {
    return assignee;
  }


  public void setAssignee(Link assignee) {
    this.assignee = assignee;
  }


  public WorkPackageLinks version(Link version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getVersion() {
    return version;
  }


  public void setVersion(Link version) {
    this.version = version;
  }


  public WorkPackageLinks parent(Link parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getParent() {
    return parent;
  }


  public void setParent(Link parent) {
    this.parent = parent;
  }


  public WorkPackageLinks logCosts(Link logCosts) {
    
    this.logCosts = logCosts;
    return this;
  }

   /**
   * Get logCosts
   * @return logCosts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOG_COSTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getLogCosts() {
    return logCosts;
  }


  public void setLogCosts(Link logCosts) {
    this.logCosts = logCosts;
  }


  public WorkPackageLinks showCosts(Link showCosts) {
    
    this.showCosts = showCosts;
    return this;
  }

   /**
   * Get showCosts
   * @return showCosts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHOW_COSTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getShowCosts() {
    return showCosts;
  }


  public void setShowCosts(Link showCosts) {
    this.showCosts = showCosts;
  }


  public WorkPackageLinks costObject(Link costObject) {
    
    this.costObject = costObject;
    return this;
  }

   /**
   * Get costObject
   * @return costObject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COST_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getCostObject() {
    return costObject;
  }


  public void setCostObject(Link costObject) {
    this.costObject = costObject;
  }


  public WorkPackageLinks costsByType(Link costsByType) {
    
    this.costsByType = costsByType;
    return this;
  }

   /**
   * Get costsByType
   * @return costsByType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COSTS_BY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Link getCostsByType() {
    return costsByType;
  }


  public void setCostsByType(Link costsByType) {
    this.costsByType = costsByType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkPackageLinks workPackageLinks = (WorkPackageLinks) o;
    return Objects.equals(this.self, workPackageLinks.self) &&
        Objects.equals(this.update, workPackageLinks.update) &&
        Objects.equals(this.schema, workPackageLinks.schema) &&
        Objects.equals(this.updateImmediately, workPackageLinks.updateImmediately) &&
        Objects.equals(this.logTime, workPackageLinks.logTime) &&
        Objects.equals(this.move, workPackageLinks.move) &&
        Objects.equals(this.copy, workPackageLinks.copy) &&
        Objects.equals(this.pdf, workPackageLinks.pdf) &&
        Objects.equals(this.atom, workPackageLinks.atom) &&
        Objects.equals(this.availableRelationCandidates, workPackageLinks.availableRelationCandidates) &&
        Objects.equals(this.activities, workPackageLinks.activities) &&
        Objects.equals(this.attachments, workPackageLinks.attachments) &&
        Objects.equals(this.addAttachment, workPackageLinks.addAttachment) &&
        Objects.equals(this.availableWatchers, workPackageLinks.availableWatchers) &&
        Objects.equals(this.relations, workPackageLinks.relations) &&
        Objects.equals(this.revisions, workPackageLinks.revisions) &&
        Objects.equals(this.watch, workPackageLinks.watch) &&
        Objects.equals(this.watchers, workPackageLinks.watchers) &&
        Objects.equals(this.addWatcher, workPackageLinks.addWatcher) &&
        Objects.equals(this.removeWatcher, workPackageLinks.removeWatcher) &&
        Objects.equals(this.addRelation, workPackageLinks.addRelation) &&
        Objects.equals(this.addChild, workPackageLinks.addChild) &&
        Objects.equals(this.changeParent, workPackageLinks.changeParent) &&
        Objects.equals(this.addComment, workPackageLinks.addComment) &&
        Objects.equals(this.previewMarkup, workPackageLinks.previewMarkup) &&
        Objects.equals(this.timeEntries, workPackageLinks.timeEntries) &&
        Objects.equals(this.ancestors, workPackageLinks.ancestors) &&
        Objects.equals(this.category, workPackageLinks.category) &&
        Objects.equals(this.type, workPackageLinks.type) &&
        Objects.equals(this.priority, workPackageLinks.priority) &&
        Objects.equals(this.project, workPackageLinks.project) &&
        Objects.equals(this.status, workPackageLinks.status) &&
        Objects.equals(this.author, workPackageLinks.author) &&
        Objects.equals(this.responsible, workPackageLinks.responsible) &&
        Objects.equals(this.assignee, workPackageLinks.assignee) &&
        Objects.equals(this.version, workPackageLinks.version) &&
        Objects.equals(this.parent, workPackageLinks.parent) &&
        Objects.equals(this.logCosts, workPackageLinks.logCosts) &&
        Objects.equals(this.showCosts, workPackageLinks.showCosts) &&
        Objects.equals(this.costObject, workPackageLinks.costObject) &&
        Objects.equals(this.costsByType, workPackageLinks.costsByType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, update, schema, updateImmediately, logTime, move, copy, pdf, atom, availableRelationCandidates, activities, attachments, addAttachment, availableWatchers, relations, revisions, watch, watchers, addWatcher, removeWatcher, addRelation, addChild, changeParent, addComment, previewMarkup, timeEntries, ancestors, category, type, priority, project, status, author, responsible, assignee, version, parent, logCosts, showCosts, costObject, costsByType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkPackageLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    updateImmediately: ").append(toIndentedString(updateImmediately)).append("\n");
    sb.append("    logTime: ").append(toIndentedString(logTime)).append("\n");
    sb.append("    move: ").append(toIndentedString(move)).append("\n");
    sb.append("    copy: ").append(toIndentedString(copy)).append("\n");
    sb.append("    pdf: ").append(toIndentedString(pdf)).append("\n");
    sb.append("    atom: ").append(toIndentedString(atom)).append("\n");
    sb.append("    availableRelationCandidates: ").append(toIndentedString(availableRelationCandidates)).append("\n");
    sb.append("    activities: ").append(toIndentedString(activities)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    addAttachment: ").append(toIndentedString(addAttachment)).append("\n");
    sb.append("    availableWatchers: ").append(toIndentedString(availableWatchers)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    revisions: ").append(toIndentedString(revisions)).append("\n");
    sb.append("    watch: ").append(toIndentedString(watch)).append("\n");
    sb.append("    watchers: ").append(toIndentedString(watchers)).append("\n");
    sb.append("    addWatcher: ").append(toIndentedString(addWatcher)).append("\n");
    sb.append("    removeWatcher: ").append(toIndentedString(removeWatcher)).append("\n");
    sb.append("    addRelation: ").append(toIndentedString(addRelation)).append("\n");
    sb.append("    addChild: ").append(toIndentedString(addChild)).append("\n");
    sb.append("    changeParent: ").append(toIndentedString(changeParent)).append("\n");
    sb.append("    addComment: ").append(toIndentedString(addComment)).append("\n");
    sb.append("    previewMarkup: ").append(toIndentedString(previewMarkup)).append("\n");
    sb.append("    timeEntries: ").append(toIndentedString(timeEntries)).append("\n");
    sb.append("    ancestors: ").append(toIndentedString(ancestors)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    responsible: ").append(toIndentedString(responsible)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    logCosts: ").append(toIndentedString(logCosts)).append("\n");
    sb.append("    showCosts: ").append(toIndentedString(showCosts)).append("\n");
    sb.append("    costObject: ").append(toIndentedString(costObject)).append("\n");
    sb.append("    costsByType: ").append(toIndentedString(costsByType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

