/*
 * OpenProject API v3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import net.jbw.openproject.client.model.Link;
/**
 * VersionLinks
 */


public class VersionLinks {
  @SerializedName("self")
  private Link self = null;

  @SerializedName("definingProject")
  private Link definingProject = null;

  @SerializedName("availableInProjects")
  private Link availableInProjects = null;

  public VersionLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }

  public VersionLinks definingProject(Link definingProject) {
    this.definingProject = definingProject;
    return this;
  }

   /**
   * Get definingProject
   * @return definingProject
  **/
  @Schema(description = "")
  public Link getDefiningProject() {
    return definingProject;
  }

  public void setDefiningProject(Link definingProject) {
    this.definingProject = definingProject;
  }

  public VersionLinks availableInProjects(Link availableInProjects) {
    this.availableInProjects = availableInProjects;
    return this;
  }

   /**
   * Get availableInProjects
   * @return availableInProjects
  **/
  @Schema(description = "")
  public Link getAvailableInProjects() {
    return availableInProjects;
  }

  public void setAvailableInProjects(Link availableInProjects) {
    this.availableInProjects = availableInProjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionLinks versionLinks = (VersionLinks) o;
    return Objects.equals(this.self, versionLinks.self) &&
        Objects.equals(this.definingProject, versionLinks.definingProject) &&
        Objects.equals(this.availableInProjects, versionLinks.availableInProjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, definingProject, availableInProjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    definingProject: ").append(toIndentedString(definingProject)).append("\n");
    sb.append("    availableInProjects: ").append(toIndentedString(availableInProjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
