/*
 * OpenProject API v3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import net.jbw.openproject.client.model.Link;
/**
 * TimeEntriesLinks
 */


public class TimeEntriesLinks {
  @SerializedName("self")
  private Link self = null;

  @SerializedName("jumpTo")
  private Link jumpTo = null;

  @SerializedName("changeSize")
  private Link changeSize = null;

  @SerializedName("nextByOffset")
  private Link nextByOffset = null;

  public TimeEntriesLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }

  public TimeEntriesLinks jumpTo(Link jumpTo) {
    this.jumpTo = jumpTo;
    return this;
  }

   /**
   * Get jumpTo
   * @return jumpTo
  **/
  @Schema(description = "")
  public Link getJumpTo() {
    return jumpTo;
  }

  public void setJumpTo(Link jumpTo) {
    this.jumpTo = jumpTo;
  }

  public TimeEntriesLinks changeSize(Link changeSize) {
    this.changeSize = changeSize;
    return this;
  }

   /**
   * Get changeSize
   * @return changeSize
  **/
  @Schema(description = "")
  public Link getChangeSize() {
    return changeSize;
  }

  public void setChangeSize(Link changeSize) {
    this.changeSize = changeSize;
  }

  public TimeEntriesLinks nextByOffset(Link nextByOffset) {
    this.nextByOffset = nextByOffset;
    return this;
  }

   /**
   * Get nextByOffset
   * @return nextByOffset
  **/
  @Schema(description = "")
  public Link getNextByOffset() {
    return nextByOffset;
  }

  public void setNextByOffset(Link nextByOffset) {
    this.nextByOffset = nextByOffset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeEntriesLinks timeEntriesLinks = (TimeEntriesLinks) o;
    return Objects.equals(this.self, timeEntriesLinks.self) &&
        Objects.equals(this.jumpTo, timeEntriesLinks.jumpTo) &&
        Objects.equals(this.changeSize, timeEntriesLinks.changeSize) &&
        Objects.equals(this.nextByOffset, timeEntriesLinks.nextByOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, jumpTo, changeSize, nextByOffset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeEntriesLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    jumpTo: ").append(toIndentedString(jumpTo)).append("\n");
    sb.append("    changeSize: ").append(toIndentedString(changeSize)).append("\n");
    sb.append("    nextByOffset: ").append(toIndentedString(nextByOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
