/*
 * OpenProject API v3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import net.jbw.openproject.client.model.TimeEntryEmbedded;
import net.jbw.openproject.client.model.TimeEntryLinks;
/**
 * TimeEntry
 */


public class TimeEntry {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("hours")
  private String hours = null;

  @SerializedName("comment")
  private Object comment = null;

  @SerializedName("spentOn")
  private LocalDate spentOn = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  @SerializedName("_embedded")
  private TimeEntryEmbedded _embedded = null;

  @SerializedName("_links")
  private TimeEntryLinks _links = null;

  public TimeEntry id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TimeEntry hours(String hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @Schema(description = "")
  public String getHours() {
    return hours;
  }

  public void setHours(String hours) {
    this.hours = hours;
  }

  public TimeEntry comment(Object comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public Object getComment() {
    return comment;
  }

  public void setComment(Object comment) {
    this.comment = comment;
  }

  public TimeEntry spentOn(LocalDate spentOn) {
    this.spentOn = spentOn;
    return this;
  }

   /**
   * Get spentOn
   * @return spentOn
  **/
  @Schema(description = "")
  public LocalDate getSpentOn() {
    return spentOn;
  }

  public void setSpentOn(LocalDate spentOn) {
    this.spentOn = spentOn;
  }

  public TimeEntry createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public TimeEntry updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public TimeEntry _embedded(TimeEntryEmbedded _embedded) {
    this._embedded = _embedded;
    return this;
  }

   /**
   * Get _embedded
   * @return _embedded
  **/
  @Schema(description = "")
  public TimeEntryEmbedded getEmbedded() {
    return _embedded;
  }

  public void setEmbedded(TimeEntryEmbedded _embedded) {
    this._embedded = _embedded;
  }

  public TimeEntry _links(TimeEntryLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public TimeEntryLinks getLinks() {
    return _links;
  }

  public void setLinks(TimeEntryLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeEntry timeEntry = (TimeEntry) o;
    return Objects.equals(this.id, timeEntry.id) &&
        Objects.equals(this.hours, timeEntry.hours) &&
        Objects.equals(this.comment, timeEntry.comment) &&
        Objects.equals(this.spentOn, timeEntry.spentOn) &&
        Objects.equals(this.createdAt, timeEntry.createdAt) &&
        Objects.equals(this.updatedAt, timeEntry.updatedAt) &&
        Objects.equals(this._embedded, timeEntry._embedded) &&
        Objects.equals(this._links, timeEntry._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hours, comment, spentOn, createdAt, updatedAt, _embedded, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    spentOn: ").append(toIndentedString(spentOn)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    _embedded: ").append(toIndentedString(_embedded)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
