/*
 * OpenProject API v3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.jbw.openproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import net.jbw.openproject.client.model.Activity;
import net.jbw.openproject.client.model.Project;
import net.jbw.openproject.client.model.User;
import net.jbw.openproject.client.model.WorkPackage;
/**
 * TimeEntryEmbedded
 */


public class TimeEntryEmbedded {
  @SerializedName("project")
  private Project project = null;

  @SerializedName("workPackage")
  private WorkPackage workPackage = null;

  @SerializedName("user")
  private User user = null;

  @SerializedName("activity")
  private Activity activity = null;

  public TimeEntryEmbedded project(Project project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @Schema(description = "")
  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public TimeEntryEmbedded workPackage(WorkPackage workPackage) {
    this.workPackage = workPackage;
    return this;
  }

   /**
   * Get workPackage
   * @return workPackage
  **/
  @Schema(description = "")
  public WorkPackage getWorkPackage() {
    return workPackage;
  }

  public void setWorkPackage(WorkPackage workPackage) {
    this.workPackage = workPackage;
  }

  public TimeEntryEmbedded user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public TimeEntryEmbedded activity(Activity activity) {
    this.activity = activity;
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  @Schema(description = "")
  public Activity getActivity() {
    return activity;
  }

  public void setActivity(Activity activity) {
    this.activity = activity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeEntryEmbedded timeEntryEmbedded = (TimeEntryEmbedded) o;
    return Objects.equals(this.project, timeEntryEmbedded.project) &&
        Objects.equals(this.workPackage, timeEntryEmbedded.workPackage) &&
        Objects.equals(this.user, timeEntryEmbedded.user) &&
        Objects.equals(this.activity, timeEntryEmbedded.activity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, workPackage, user, activity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeEntryEmbedded {\n");
    
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    workPackage: ").append(toIndentedString(workPackage)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
